class GameUI{
constructor(game){this.game=game;this.boardEl=document.getElementById('board');this.scoreEl=document.getElementById('score-value');this.movesEl=document.getElementById('moves-value');this.timerEl=document.getElementById('timer-value');this.undoBtn=document.getElementById('btn-undo');this.newGameBtn=document.getElementById('btn-new-game');this.autoBtn=document.getElementById('btn-autocomplete');this.winOverlay=document.getElementById('win-overlay');this.loseOverlay=document.getElementById('lose-overlay');this.winScore=document.getElementById('win-score');this.winMoves=document.getElementById('win-moves');this.winTime=document.getElementById('win-time');this.settingsBtn=document.getElementById('btn-settings');this.settingsOverlay=document.getElementById('settings-overlay');this.closeSettingsBtn=document.getElementById('btn-close-settings');this.tHandedness=document.getElementById('toggle-handedness');this.tDarkMode=document.getElementById('toggle-darkmode');this.tScore=document.getElementById('toggle-score');this.tMoves=document.getElementById('toggle-moves');this.tTime=document.getElementById('toggle-time');this.statScore=document.getElementById('stat-score');this.statMoves=document.getElementById('stat-moves');this.statTime=document.getElementById('stat-time');this.settings={rightHanded:true,darkMode:false,showScore:true,showMoves:true,showTime:true};this._loadSettings();this._setupCallbacks();this._setupEventListeners()}
_loadSettings(){try{const s=localStorage.getItem('solitaire_settings');if(s)this.settings={...this.settings,...JSON.parse(s)}}catch(e){}this.tHandedness.checked=this.settings.rightHanded;this.tDarkMode.checked=this.settings.darkMode;this.tScore.checked=this.settings.showScore;this.tMoves.checked=this.settings.showMoves;this.tTime.checked=this.settings.showTime;this._applySettings(false)}
_saveSettings(){try{localStorage.setItem('solitaire_settings',JSON.stringify(this.settings))}catch(e){}}
_applySettings(reRender=true){if(this.settings.darkMode)document.body.classList.add('dark-theme');else document.body.classList.remove('dark-theme');this.statScore.classList.toggle('hidden',!this.settings.showScore);this.statMoves.classList.toggle('hidden',!this.settings.showMoves);this.statTime.classList.toggle('hidden',!this.settings.showTime);if(reRender)this.render()}
_setupCallbacks(){this.game.onStateChange=()=>{this.render();if(this.game.canAutoComplete())this.autoBtn.classList.add('show');else this.autoBtn.classList.remove('show')};this.game.onScoreChange=(s,m)=>{this.scoreEl.textContent=s;this.movesEl.textContent=m;this.undoBtn.classList.toggle('disabled',!this.game.canUndo())};this.game.onTimerChange=()=>{this.timerEl.textContent=this.game.getFormattedTime()};this.game.onWin=(s,m,t)=>this._showWin(s,m,t)}
_setupEventListeners(){this.newGameBtn.addEventListener('click',()=>this._handleNewGame());this.undoBtn.addEventListener('click',()=>this._handleUndo());this.autoBtn.addEventListener('click',()=>this._startAuto());document.getElementById('win-new-game').addEventListener('click',()=>{this.winOverlay.classList.remove('show');this._handleNewGame()});document.getElementById('lose-new-game').addEventListener('click',()=>{this.loseOverlay.classList.remove('show');this._handleNewGame()});document.getElementById('lose-undo').addEventListener('click',()=>{this.loseOverlay.classList.remove('show');this.game.undo()});document.addEventListener('touchstart',(e)=>{if(e.touches.length>1)e.preventDefault()},{passive:false});let lte=0;document.addEventListener('touchend',(e)=>{const n=Date.now();if(n-lte<=300)e.preventDefault();lte=n},{passive:false});this.settingsBtn.addEventListener('click',()=>this.settingsOverlay.classList.add('show'));this.closeSettingsBtn.addEventListener('click',()=>this.settingsOverlay.classList.remove('show'));this.tHandedness.addEventListener('change',e=>{this.settings.rightHanded=e.target.checked;this._saveSettings();this._applySettings()});this.tDarkMode.addEventListener('change',e=>{this.settings.darkMode=e.target.checked;this._saveSettings();this._applySettings(false)});this.tScore.addEventListener('change',e=>{this.settings.showScore=e.target.checked;this._saveSettings();this._applySettings(false)});this.tMoves.addEventListener('change',e=>{this.settings.showMoves=e.target.checked;this._saveSettings();this._applySettings(false)});this.tTime.addEventListener('change',e=>{this.settings.showTime=e.target.checked;this._saveSettings();this._applySettings(false)})}
_handleNewGame(){const stockEl=document.getElementById('stock');const sR=stockEl?stockEl.getBoundingClientRect():{left:0,top:0};const cards=this.boardEl.querySelectorAll('.card:not(.empty-pile)');let maxD=0;cards.forEach((c,i)=>{const cR=c.getBoundingClientRect();const dx=sR.left-cR.left;const dy=sR.top-cR.top;const d=i*0.01;maxD=Math.max(maxD,d);c.style.transition='transform 0.3s cubic-bezier(0.5, 0, 0.8, 0.2) '+d+'s, opacity 0.2s ease '+(d+0.1)+'s';c.style.transform='translate('+dx+'px, '+dy+'px) scale(0.5)';c.style.zIndex='9999';c.style.opacity='0'});setTimeout(()=>{this.game.newGame();this._animDeal()},(maxD+0.3)*1000+100)}
_handleUndo(){if(this.game.canUndo()){this.game.undo();this.undoBtn.classList.add('pulse');setTimeout(()=>this.undoBtn.classList.remove('pulse'),400)}}
_animDeal(){const stockEl=document.getElementById('stock');if(!stockEl)return;const sR=stockEl.getBoundingClientRect();const cards=this.boardEl.querySelectorAll('.tableau-row .card:not(.empty-pile)');let i=0;cards.forEach(c=>{const cR=c.getBoundingClientRect();const dx=sR.left-cR.left;const dy=sR.top-cR.top;c.style.transition='none';c.style.opacity='0';c.style.transform='translate('+dx+'px, '+dy+'px) scale(0.5)';c.style.zIndex='99';c.offsetHeight;const d=i*0.05;requestAnimationFrame(()=>{c.style.transition='transform 0.4s cubic-bezier(0.2, 0.8, 0.2, 1) '+d+'s, opacity 0.2s ease '+d+'s';c.style.opacity='1';c.style.transform='translate(0, 0) scale(1)';setTimeout(()=>{c.style.transition='';c.style.zIndex=''},(d+0.4)*1000+50)});i++})}
render(){const oldPos={};const oldFaceUp={};document.querySelectorAll('.card').forEach(c=>{if(c.dataset.cardId){oldPos[c.dataset.cardId]=c.getBoundingClientRect();oldFaceUp[c.dataset.cardId]=c.dataset.faceUp==='true'}});const stockEl=document.getElementById('stock');const oldStockPos=stockEl?stockEl.getBoundingClientRect():null;this.boardEl.innerHTML='';const tr=document.createElement('div');tr.className='top-row';const se=this._renderStock(),we=this._renderWaste(),sp=document.createElement('div');sp.className='spacer';const fs=[];for(let i=0;i<4;i++)fs.push(this._renderFoundation(i));if(this.settings.rightHanded){fs.forEach(f=>tr.appendChild(f));tr.appendChild(sp);tr.appendChild(we);tr.appendChild(se)}else{tr.appendChild(se);tr.appendChild(we);tr.appendChild(sp);fs.forEach(f=>tr.appendChild(f))}this.boardEl.appendChild(tr);const tbr=document.createElement('div');tbr.className='tableau-row';for(let i=0;i<7;i++)tbr.appendChild(this._renderTableau(i));this.boardEl.appendChild(tbr);requestAnimationFrame(()=>{document.querySelectorAll('.card').forEach(c=>{const id=c.dataset.cardId;if(!id)return;let oldR=oldPos[id];const wasFaceUp=oldFaceUp[id];if(!oldR&&oldStockPos&&c.closest('#waste'))oldR=oldStockPos;if(oldR){const newR=c.getBoundingClientRect();const dx=oldR.left-newR.left;const dy=oldR.top-newR.top;const isFlip=!wasFaceUp&&c.dataset.faceUp==='true';if(dx!==0||dy!==0){c.style.transform='translate('+dx+'px, '+dy+'px)'+(isFlip?' scaleX(0)':'');c.style.transition='none';c.style.zIndex='9999';requestAnimationFrame(()=>{c.style.transition='transform 0.25s ease-out';c.style.transform='translate(0, 0) scaleX(1)';setTimeout(()=>{c.style.zIndex='';c.style.transition=''},250)})}else if(isFlip){c.classList.add('card-flip-enter')}}})})}
_renderStock(){const el=document.createElement('div');el.className='pile stock-pile';el.id='stock';if(this.game.state.stock.length>0){const ce=this._cardBack(null);ce.addEventListener('pointerdown',(e)=>{e.preventDefault();this.game.drawFromStock()});el.appendChild(ce);const b=document.createElement('span');b.className='pile-count';b.textContent=this.game.state.stock.length;el.appendChild(b)}else{const ee=document.createElement('div');ee.className='card empty-pile recycle-indicator';ee.innerHTML='<span class="recycle-icon">↻</span>';ee.addEventListener('pointerdown',(e)=>{e.preventDefault();this.game.drawFromStock()});el.appendChild(ee)}return el}
_renderWaste(){const el=document.createElement('div');el.className='pile waste-pile';el.id='waste';if(this.game.state.waste.length>0){this.game.state.waste.forEach((card,ci)=>{const ce=this._cardFace(card);ce.classList.add('stacked');if(ci===this.game.state.waste.length-1)this._addInteraction(ce,card,'waste',0,ci);el.appendChild(ce)})}else{el.appendChild(this._emptySlot())}return el}
_renderFoundation(idx){const el=document.createElement('div');el.className='pile foundation-pile';el.dataset.foundationIndex=idx;const f=this.game.state.foundations[idx];if(f.length>0){f.forEach(card=>{const ce=this._cardFace(card);ce.classList.add('stacked');el.appendChild(ce)})}else{el.appendChild(this._emptySlot())}return el}
_renderTableau(idx){const el=document.createElement('div');el.className='tableau-column';el.dataset.tableauIndex=idx;const col=this.game.state.tableau[idx];if(col.length===0){el.appendChild(this._emptySlot())}else{let currentTop=0;col.forEach((card,ci)=>{const ce=card.faceUp?this._cardFace(card):this._cardBack(card);ce.style.top=currentTop+'px';currentTop+=card.faceUp?28:14;ce.classList.add('stacked');if(card.faceUp)this._addInteraction(ce,card,'tableau',idx,ci);el.appendChild(ce)})}return el}
_cardFace(card){const el=document.createElement('div');el.className='card face-up '+card.color;el.dataset.cardId=card.id;el.dataset.faceUp='true';const showSuit=['A','J','Q','K'].includes(card.value);const suitHtml=showSuit?'<span class="card-suit">'+card.symbol+'</span>':'';const tl=document.createElement('div');tl.className='card-corner top-left';tl.innerHTML='<span class="card-value">'+card.value+'</span>'+suitHtml;const ct=document.createElement('div');ct.className='card-center';ct.innerHTML=this._centerContent(card);const br=document.createElement('div');br.className='card-corner bottom-right';br.innerHTML='<span class="card-value">'+card.value+'</span>'+suitHtml;el.appendChild(tl);el.appendChild(ct);el.appendChild(br);return el}
_centerContent(card){const s=card.symbol,v=card.value;if(v==='A')return '<span class="center-suit large">'+s+'</span>';if(v==='K'||v==='Q'||v==='J'){let sym='';if(v==='K')sym='🤴🏻';else if(v==='Q')sym='👸🏻';else if(v==='J')sym='⚔️';return '<span class="center-suit large" style="font-size:20px;line-height:1;filter:drop-shadow(0 2px 4px rgba(0,0,0,0.2))">'+sym+'</span>'}const n=parseInt(v);if(!isNaN(n)){let p='';for(let i=0;i<n;i++)p+='<span class="pip">'+s+'</span>';return '<div class="pips pips-'+n+'">'+p+'</div>'}return '<span class="center-suit">'+s+'</span>'}
_cardBack(card){const el=document.createElement('div');el.className='card face-down';if(card){el.dataset.cardId=card.id;el.dataset.faceUp='false'}const inner=document.createElement('div');inner.className='card-back-design';const pat=document.createElement('div');pat.className='back-pattern';inner.appendChild(pat);el.appendChild(inner);return el}
_emptySlot(){const el=document.createElement('div');el.className='card empty-pile';return el}
_addInteraction(ce,card,st,si,ci){let tsp=null,isDrag=false,dragClone=null,dragCards=[];
ce.addEventListener('pointerdown',(e)=>{e.stopPropagation();tsp={x:e.clientX,y:e.clientY};isDrag=false;if(st==='tableau'){const col=this.game.state.tableau[si];dragCards=[];for(let i=ci;i<col.length;i++)dragCards.push(col[i])}else dragCards=[card]});
ce.addEventListener('pointermove',(e)=>{if(!tsp)return;const dx=e.clientX-tsp.x,dy=e.clientY-tsp.y;if(!isDrag&&(Math.abs(dx)>8||Math.abs(dy)>8)){isDrag=true;dragClone=this._dragGhost(dragCards);ce.classList.add('dragging-source');ce.setPointerCapture(e.pointerId)}if(isDrag&&dragClone){dragClone.style.left=(e.clientX-35)+'px';dragClone.style.top=(e.clientY-25)+'px'}});
ce.addEventListener('pointerup',(e)=>{let isTap=!isDrag;if(isDrag){if(dragClone){document.body.removeChild(dragClone);dragClone=null}ce.classList.remove('dragging-source');const dt=this._findDrop(e.clientX,e.clientY);if(dt&&(dt.type!==st||dt.index!==si)){let ok=false;if(dt.type==='foundation'){if(st==='waste')ok=this.game.moveWasteToFoundation(dt.index);else if(st==='tableau')ok=this.game.moveTableauToFoundation(si,dt.index)}else if(dt.type==='tableau'){if(st==='waste')ok=this.game.moveWasteToTableau(dt.index);else if(st==='tableau')ok=this.game.moveTableauToTableau(si,dt.index,ci);else if(st==='foundation')ok=this.game.moveFoundationToTableau(si,dt.index)}if(ok)setTimeout(()=>this._checkOver(),300)}else{isTap=true}}if(isTap){let moved=this.game.autoMoveToFoundation(card,st,si,ci);if(!moved){if(st==='waste'){for(let i=0;i<7;i++){if(this.game.canMoveToTableau(card,i)){moved=this.game.moveWasteToTableau(i);break}}}else if(st==='tableau'){for(let i=0;i<7;i++){if(i!==si&&this.game.canMoveToTableau(card,i)){moved=this.game.moveTableauToTableau(si,i,ci);break}}}}if(moved)setTimeout(()=>this._checkOver(),300);else{ce.classList.add('shake');setTimeout(()=>ce.classList.remove('shake'),400)}}tsp=null;isDrag=false;dragCards=[]});
ce.addEventListener('pointercancel',()=>{if(dragClone){document.body.removeChild(dragClone);dragClone=null}ce.classList.remove('dragging-source');tsp=null;isDrag=false})}
_findDrop(x,y){const fs=document.querySelectorAll('.foundation-pile');for(let i=0;i<fs.length;i++){const r=fs[i].getBoundingClientRect();if(x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom)return{type:'foundation',index:i}}const cs=document.querySelectorAll('.tableau-column');for(let i=0;i<cs.length;i++){const r=cs[i].getBoundingClientRect();if(x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom)return{type:'tableau',index:parseInt(cs[i].dataset.tableauIndex)}}return null}
_dragGhost(cards){const g=document.createElement('div');g.className='drag-ghost';cards.forEach((c,i)=>{const ce=this._cardFace(c);ce.style.position='absolute';ce.style.top=i*28+'px';ce.style.pointerEvents='none';g.appendChild(ce)});g.style.position='fixed';g.style.zIndex='10000';g.style.pointerEvents='none';g.style.width='70px';g.style.opacity='0.9';g.style.transform='rotate(3deg) scale(1.05)';document.body.appendChild(g);return g}
_checkOver(){if(this.game.gameWon||this.game.gameOver)return;if(!this.game.hasMovesLeft()){this.game.gameOver=true;this.game.stopTimer();setTimeout(()=>this.loseOverlay.classList.add('show'),500)}}
_showWin(score,moves,time){this.winScore.textContent=score;this.winMoves.textContent=moves;const m=Math.floor(time/60),s=time%60;this.winTime.textContent=m.toString().padStart(2,'0')+':'+s.toString().padStart(2,'0');const cards=this.boardEl.querySelectorAll('.card.face-up');cards.forEach((c,i)=>{setTimeout(()=>{const a=(Math.random()-0.5)*360;const tx=(Math.random()-0.5)*window.innerWidth;const ty=window.innerHeight+100;c.style.transition='transform 1s ease-in';c.style.transform='translate('+tx+'px,'+ty+'px) rotate('+a+'deg)'},i*50)});this._confetti();setTimeout(()=>this.winOverlay.classList.add('show'),2000)}
_confetti(){const cc=document.createElement('div');cc.className='confetti-container';document.body.appendChild(cc);const colors=['#ff6b6b','#ffd93d','#6bcb77','#4d96ff','#ff6eb4','#a855f7'];for(let i=0;i<80;i++){const c=document.createElement('div');c.className='confetti';c.style.left=Math.random()*100+'%';c.style.backgroundColor=colors[Math.floor(Math.random()*colors.length)];c.style.animationDelay=Math.random()*2+'s';c.style.animationDuration=(2+Math.random()*3)+'s';const sz=6+Math.random()*8;c.style.width=sz+'px';c.style.height=sz*0.6+'px';cc.appendChild(c)}setTimeout(()=>cc.remove(),6000)}
_startAuto(){this.autoBtn.classList.remove('show');this._doNextAuto()}
_doNextAuto(){if(this.game.gameWon)return;let moved=false;for(let c=0;c<7;c++){const col=this.game.state.tableau[c];if(col.length>0){const card=this.game.getTopCard(col);for(let f=0;f<4;f++){if(this.game.canMoveToFoundation(card,f)){moved=this.game.moveTableauToFoundation(c,f);break}}}if(moved)break}if(moved)setTimeout(()=>this._doNextAuto(),200)}
init(){this.game.newGame();this._animDeal()}
}